"""
Link-level DMIMO simulator: transmit *actual bits* over the multi-TRP downlink
and report BLER / BER / throughput, reusing the existing channel / precoder /
error building blocks from ``dmimo`` and **Sionna's standard PHY building blocks**
(``ResourceGrid`` + ``KroneckerPilotPattern`` + ``ResourceGridMapper`` +
``LSChannelEstimator`` (perfect CSI uses the true channel) + ``LMMSEEqualizer`` +
``ApplyOFDMChannel``), mirroring the official Sionna tutorial
``MIMO_OFDM_Transmissions_over_CDL``.

PHY chain:

    info bits --(CRC +)LDPC5G--> codeword --QAM--> data symbols [B,1,rank,n_data]
    ResourceGridMapper places data + Kronecker QPSK pilots (dedicated DMRS symbols)
    y = H_eff x + AWGN            (ApplyOFDMChannel; H_eff static across symbols)
    LS / perfect channel estimation -> LMMSE equalizer -> Demapper -> decode

``H_eff`` is built exactly as in the (system-level) ``DMIMODownlink``: precoding
uses the *clean* channel, the error-corrupted channel is used for combining.

Resource grid / pilots
----------------------
The transmission spans ``num_symbols`` OFDM symbols x ``n_subcarriers``
subcarriers (``ResourceGrid``). Dedicated DMRS symbol(s) (index ``dmrs_symbol``,
front-loaded as in 5G mapping type A) carry the pilots generated by
``KroneckerPilotPattern``: unit-power random QPSK sequences, non-overlapping
across the ``rank`` streams, on *all* subcarriers of the pilot symbols. All other
symbols carry data. ``pilot_boost_db`` scales the pilots (DMRS energy boost,
like Sionna's ``beta``). ``est_density`` is accepted for backward compatibility
but is superseded: with the Kronecker pattern every subcarrier of a DMRS symbol
is a pilot.

Noise / SNR convention (Sionna-consistent)
------------------------------------------
``no = 10**(-snr_db/10)`` is the **total AWGN variance per resource element** for
a unit-power transmit symbol (Sionna's ``AWGN`` / ``ApplyOFDMChannel(add_awgn=True)``
add complex Gaussian noise of variance ``no/2`` per real dimension, total ``no``),
so ``SNR = 1/no``. The equalizer uses the same ``no``.
"""
from __future__ import annotations

import math

import numpy as np
import torch

from sionna.phy.channel import ApplyOFDMChannel
from sionna.phy.fec.ldpc import LDPC5GEncoder, LDPC5GDecoder
from sionna.phy.mapping import Mapper, Demapper
from sionna.phy.mimo import StreamManagement
from sionna.phy.nr import TBEncoder, TBDecoder
from sionna.phy.ofdm import (ResourceGrid, ResourceGridMapper, LSChannelEstimator,
                             LMMSEEqualizer, PilotPattern)

def _dense_pilot_pattern(num_streams, num_ofdm_symbols, fft_size, pilot_syms, device):
    """Interleaved-comb pilot pattern with full per-stream subcarrier coverage.

    Sionna's ``KroneckerPilotPattern`` gives each stream a frequency comb with
    spacing ``num_tx*num_streams_per_tx`` (= rank), so at rank>=2 every stream has
    pilots on only a fraction of the subcarriers and ``LSChannelEstimator`` must
    interpolate in frequency. That interpolation bias is systematic and is *not*
    reflected in the returned ``err_var``, which pins the BLER to a high-SNR floor
    (measured ~0.1 with "nn", ~0.03 with "lin" at 240 SC / rank 2, while rank 1 -
    full coverage - gives BLER=0).

    This pattern uses ``len(pilot_syms)>=2`` DMRS symbols with the comb offset
    alternating per symbol: symbol ``i``, stream ``s`` carries *nonzero* pilots on
    subcarriers ``(s+i) mod num_streams`` and *zero* on the complementary comb, so
    the whole pilot symbols are reserved (no cross-stream data interference, as in
    the Kronecker pattern). Every subcarrier of every stream is a nonzero pilot in
    exactly one of the pilot symbols, hence the channel is estimated per subcarrier
    and the frequency-interpolation floor disappears. Pilot RE count per stream is
    ``len(pilot_syms)*fft_size`` (vs ``fft_size`` for Kronecker): the extra symbol
    is the physical cost of full per-stream coverage.
    """
    num_tx = 1
    mask = np.zeros([num_tx, num_streams, num_ofdm_symbols, fft_size], dtype=bool)
    vals = np.zeros([num_tx, num_streams, num_ofdm_symbols, fft_size], dtype=np.complex64)
    for s in range(num_streams):
        for i, sym in enumerate(pilot_syms):
            mask[0, s, sym, :] = True               # reserve whole pilot symbols
            parity = (s + i) % num_streams
            sub = np.arange(parity, fft_size, num_streams)
            vals[0, s, sym, sub] = 1.0 + 0.0j       # interleaved comb (zeros elsewhere)
    # pilots must be [num_tx, num_streams, num_pilots] in ascending
    # (symbol-major, subcarrier-minor) mask order (matches the LS estimator's
    # `argsort(..., stable=True)` gathering).
    pilots = np.stack([vals[0, s][mask[0, s]] for s in range(num_streams)])[None]
    return PilotPattern(mask=mask, pilots=pilots, normalize=False, device=device)


class LinkLevelDMIMO:
    """Link-level (bit-processing) DMIMO evaluator producing BLER / BER / throughput.

    Parameters
    ----------
    ----------
    link : DMIMODownlink
        Provides the channel, precoder and error model (built with ``build_link``).
    qam_order : int
        QAM constellation size (16 -> 4 bits/symbol).
    code_rate : float
        Target transport-block code rate (info bits / coded bits).
    rank : int
        Number of layers. Must match the precoder used at evaluation.
    use_channel_estimation : bool
        Enable DMRS-based LS channel estimation. If ``False`` the receiver uses
        the perfect effective channel for detection.
    est_density : float
        Accepted for backward compatibility (superseded by the Sionna Kronecker
        pilot pattern, which pilots every subcarrier of the DMRS symbols).
    pilot_boost_db : float
        DMRS pilot energy boost in dB relative to a data symbol (default 0 dB).
    n_symbols : int
        Number of OFDM symbols in the slot (time-frequency resource grid).
    dmrs_symbol : int
        Index of the (first) pilot-only DMRS symbol (5G mapping type A -> 2).
    num_dmrs_symbols : int
        Number of pilot-only DMRS symbols.
    use_crc : bool
        Use the 5G NR transport-block encoder/decoder with TB CRC error
        detection. If ``False`` a plain LDPC code with full-bit comparison is used.
    device : str
    """

    def __init__(self, link, qam_order=16, code_rate=0.5, rank=1,
                 use_channel_estimation=False, est_density=0.5, use_crc=True,
                 pilot_boost_db=0.0, n_symbols=14, dmrs_symbol=2, num_dmrs_symbols=1,
                 device=None):
        self.link = link
        self.rank = int(rank)
        self.qam_order = int(qam_order)
        self.bits_sym = int(math.log2(qam_order))
        self.n_data = int(link.n_subcarriers)       # subcarriers (data uses all of them)
        self.use_channel_estimation = bool(use_channel_estimation)
        self.use_crc = bool(use_crc)
        if device is None:                        # resolve before building Sionna blocks
            device = "cuda:0" if torch.cuda.is_available() else "cpu"
        self.device = device

        self.n_symbols = int(n_symbols)
        self.dmrs_symbol = int(dmrs_symbol)
        self.num_dmrs_symbols = int(num_dmrs_symbols)
        if not (0 <= self.dmrs_symbol < self.n_symbols):
            raise ValueError(f"dmrs_symbol {dmrs_symbol} out of range [0, {self.n_symbols}).")
        if self.num_dmrs_symbols < 1:
            raise ValueError("num_dmrs_symbols must be >= 1.")
        self.pilot_boost_db = float(pilot_boost_db)
        self.pilot_amp = math.sqrt(10.0 ** (self.pilot_boost_db / 10.0))

        # ---- Sionna resource grid with DMRS pilots ---------------------------
        # Dedicated DMRS symbol(s). Default: KroneckerPilotPattern puts unit-power
        # random QPSK pilots on a per-stream comb (spacing = rank, non-overlapping
        # across the ``rank`` streams; needs fft_size % (num_tx*num_streams_per_tx)==0).
        # With >=2 DMRS symbols and rank>=2 we instead use an interleaved comb so every
        # stream has a pilot on EVERY subcarrier (across the pilot symbols): the LS
        # estimator then needs no frequency interpolation -> no high-SNR BLER floor.
        pilot_syms = [(self.dmrs_symbol + i) % self.n_symbols
                      for i in range(self.num_dmrs_symbols)]
        scs = getattr(link.error.timing, "d_f", 30e3)   # subcarrier spacing (Hz)
        if self.num_dmrs_symbols >= 2 and self.rank >= 2:
            pp = _dense_pilot_pattern(self.rank, self.n_symbols, self.n_data,
                                      pilot_syms, device)
            self.resource_grid = ResourceGrid(
                num_ofdm_symbols=self.n_symbols,
                fft_size=self.n_data,
                subcarrier_spacing=scs,
                num_tx=1,
                num_streams_per_tx=self.rank,
                cyclic_prefix_length=0,
                num_guard_carriers=(0, 0),
                dc_null=False,
                pilot_pattern=pp,
                device=device)
        else:
            self.resource_grid = ResourceGrid(
                num_ofdm_symbols=self.n_symbols,
                fft_size=self.n_data,
                subcarrier_spacing=scs,
                num_tx=1,
                num_streams_per_tx=self.rank,
                cyclic_prefix_length=0,
                num_guard_carriers=(0, 0),
                dc_null=False,
                pilot_pattern="kronecker",
                pilot_ofdm_symbol_indices=pilot_syms,
                device=device)
        # DMRS energy boost (scale the generated pilots, like Sionna ``beta``)
        if self.pilot_amp != 1.0:
            self.resource_grid.pilot_pattern.pilots.mul_(self.pilot_amp)
        self.num_pilots = int(self.resource_grid.num_pilot_symbols)

        # ---- Sionna PHY blocks ---------------------------------------------
        self.sm = StreamManagement(np.array([[1]]), self.rank)
        self.rg_mapper = ResourceGridMapper(self.resource_grid, device=device)
        self.ls_est = LSChannelEstimator(self.resource_grid,
                                         interpolation_type="nn", device=device)
        self.lmmse = LMMSEEqualizer(self.resource_grid, self.sm, device=device)
        self.channel = ApplyOFDMChannel(add_awgn=True, device=device)

        # ---- data / coded bit budget ---------------------------------------
        # ``resource_grid.num_data_symbols`` is the data RE count **per stream**
        # (Kronecker pilots share the DMRS symbols for all streams).
        self.n_data_sym = int(self.resource_grid.num_data_symbols)
        self.n = self.n_data_sym * self.rank * self.bits_sym
        self.k = int(round(self.n * code_rate))          # target info bits
        if self.k < 1:
            raise ValueError("Resulting TB too small (k<1); lower code_rate/rank.")

        # ---- TX / RX blocks ------------------------------------------------
        self.mapper = Mapper("qam", self.bits_sym, device=device)
        self.demapper = Demapper("app", "qam", self.bits_sym, device=device)
        if use_crc:
            self.enc = TBEncoder(target_tb_size=self.k, num_coded_bits=self.n,
                                 target_coderate=code_rate,
                                 num_bits_per_symbol=self.bits_sym,
                                 num_layers=self.rank, channel_type="PDSCH",
                                 device=device)
            self.dec = TBDecoder(self.enc, device=device)
            self.tb_size = self.enc.tb_size
            self.crc_length = self.enc.tb_crc_encoder.crc_length
        else:
            self.enc = LDPC5GEncoder(self.k, self.n,
                                     num_bits_per_symbol=self.bits_sym,
                                     device=device)
            self.dec = LDPC5GDecoder(self.enc, device=device)
            self.tb_size = self.k
            self.crc_length = 0

    def block(self, batch_size, snr_db, precoder, device=None, seed=None):
        """Run one batch of transport blocks -> (bler, ber, info_bits).

        Inference-only: wrapped in ``torch.no_grad()`` so learnable precoders do
        not build an autograd graph through the channel / LS / LMMSE / LDPC
        decoding (that would explode GPU memory, e.g. ~11 GB for the NN-PMI
        mixer at batch 32 vs ~0.5 GB with no_grad).
        """
        if seed is not None:
            torch.manual_seed(seed)

        with torch.no_grad():
            return self._block_impl(batch_size, snr_db, precoder, device)

    def _block_impl(self, batch_size, snr_db, precoder, device=None):
        """``block()`` body (must be called under ``torch.no_grad()``)."""
        device = device or self.device
        no = 10.0 ** (-snr_db / 10.0)   # total AWGN variance (unit-power signal)
        h = self.link.channel.sample(batch_size, device).to(device)   # [B,K,D,Nt,N]
        h_err = self.link.error.apply(h)                   # with errors
        w = precoder(h_err) if getattr(precoder, "precodes_from_errors", False) else precoder(h)
        H_eff = self.link._combine(h_err, w)               # [B, N_rx, rank, N_sc]

        bits = torch.randint(0, 2, (batch_size, self.k),
                             dtype=torch.float32, device=device)
        cw = self.enc(bits)                                # [B, n]
        # map codeword bits onto per-stream data REs
        cw_r = cw.reshape(batch_size, 1, self.rank, self.n_data_sym, self.bits_sym)
        s = self.mapper(cw_r).squeeze(-1)                  # [B, 1, rank, n_data]
        x_rg = self.rg_mapper(s)                           # [B, 1, rank, n_sym, N_sc]

        # ---- effective channel (static across symbols) + AWGN --------------
        # Format H_eff as the Sionna channel tensor
        # [B, num_rx=1, N_rx, num_tx=1, rank, n_sym, N_sc]
        h7 = (H_eff.unsqueeze(1).unsqueeze(3).unsqueeze(5)
                   .expand(batch_size, 1, H_eff.shape[1], 1, self.rank,
                           self.n_symbols, self.n_data).contiguous())
        y = self.channel(x_rg, h7, no)                     # [B, 1, N_rx, n_sym, N_sc]

        # ---- channel estimation + LMMSE + demap + decode -------------------
        if self.use_channel_estimation:
            h_hat, err_var = self.ls_est(y, no)
        else:
            h_hat, err_var = h7, 0.0   # perfect CSI (true channel, no error)
        x_hat, no_eff = self.lmmse(y, h_hat, err_var, no)  # [B,1,rank,n_data]
        llr = self.demapper(x_hat, no_eff)                 # [B,1,rank,n_data,bits]
        llr = llr.reshape(batch_size, self.n)

        # ---- decode + error detection --------------------------------------
        if self.use_crc:
            b_hat, crc_ok = self.dec(llr)                  # [B,k], [B] True=OK
            bler = float((~crc_ok).float().mean().item())
        else:
            b_hat = self.dec(llr)[..., :self.k]
            bler = float((b_hat != bits).any(dim=-1).float().mean().item())
        ber = float((b_hat != bits).float().mean().item())
        return bler, ber, self.k

    def _sample(self, batch_size, device=None):
        """Draw one channel/error/bits realization for a batch."""
        device = device or self.device
        h = self.link.channel.sample(batch_size, device).to(device)   # [B,K,D,Nt,N]
        h_err = self.link.error.apply(h)                              # with errors
        bits = torch.randint(0, 2, (batch_size, self.k),
                             dtype=torch.float32, device=device)
        return h, h_err, bits

    def evaluate_many(self, batch_size, snr_db, precoders, device=None, seed=None,
                      num_batches=1):
        """Run several precoders on the *same* channel/bits realizations.

        For each batch, one channel/error/bits realization is sampled and shared
        by all precoders. Results are accumulated over ``num_batches`` Monte-Carlo
        batches, giving a more stable BLER/BER estimate without requiring one huge
        batch in GPU memory.
        """
        if seed is not None:
            torch.manual_seed(seed)

        accum = {
            name: {"blocks": 0, "block_errors": 0.0, "bit_errors": 0.0, "bits": 0}
            for name in precoders
        }
        with torch.no_grad():
            for _ in range(int(num_batches)):
                h, h_err, bits = self._sample(batch_size, device)
                for name, pc in precoders.items():
                    bler, ber, k = self._block_from_tensors(h, h_err, bits, snr_db, pc, device)
                    a = accum[name]
                    a["blocks"] += batch_size
                    a["block_errors"] += bler * batch_size
                    a["bits"] += batch_size * k
                    a["bit_errors"] += ber * batch_size * k

        return {
            name: (
                a["block_errors"] / a["blocks"],
                a["bit_errors"] / a["bits"],
                self.k,
            )
            for name, a in accum.items()
        }

    def _block_from_tensors(self, h, h_err, bits, snr_db, precoder, device=None):
        """Evaluate one precoder on pre-sampled channel/bits tensors."""
        device = device or self.device
        batch_size = h.shape[0]
        no = 10.0 ** (-snr_db / 10.0)   # total AWGN variance (unit-power signal)
        w = precoder(h_err) if getattr(precoder, "precodes_from_errors", False) else precoder(h)
        H_eff = self.link._combine(h_err, w)               # [B, N_rx, rank, N_sc]

        cw = self.enc(bits)                                # [B, n]
        # map codeword bits onto per-stream data REs
        cw_r = cw.reshape(batch_size, 1, self.rank, self.n_data_sym, self.bits_sym)
        s = self.mapper(cw_r).squeeze(-1)                  # [B, 1, rank, n_data]
        x_rg = self.rg_mapper(s)                           # [B, 1, rank, n_sym, N_sc]

        # ---- effective channel (static across symbols) + AWGN --------------
        # Format H_eff as the Sionna channel tensor
        # [B, num_rx=1, N_rx, num_tx=1, rank, n_sym, N_sc]
        h7 = (H_eff.unsqueeze(1).unsqueeze(3).unsqueeze(5)
                   .expand(batch_size, 1, H_eff.shape[1], 1, self.rank,
                           self.n_symbols, self.n_data).contiguous())
        y = self.channel(x_rg, h7, no)                     # [B, 1, N_rx, n_sym, N_sc]

        # ---- channel estimation + LMMSE + demap + decode -------------------
        if self.use_channel_estimation:
            h_hat, err_var = self.ls_est(y, no)
        else:
            h_hat, err_var = h7, 0.0   # perfect CSI (true channel, no error)
        x_hat, no_eff = self.lmmse(y, h_hat, err_var, no)  # [B,1,rank,n_data]
        llr = self.demapper(x_hat, no_eff)                 # [B,1,rank,n_data,bits]
        llr = llr.reshape(batch_size, self.n)

        # ---- decode + error detection --------------------------------------
        if self.use_crc:
            b_hat, crc_ok = self.dec(llr)                  # [B,k], [B] True=OK
            bler = float((~crc_ok).float().mean().item())
        else:
            b_hat = self.dec(llr)[..., :self.k]
            bler = float((b_hat != bits).any(dim=-1).float().mean().item())
        ber = float((b_hat != bits).float().mean().item())
        return bler, ber, self.k


    def throughput_bps(self, bler: float, slot_duration: float = 0.5e-3) -> float:
        """Achievable throughput assuming BLER-errored blocks are lost."""
        return self.k * (1.0 - bler) / slot_duration
